version: '3'
services:
    docker-piwigo:
        container_name: docker-piwigo
        build: .
        # image: docker-piwigo
        volumes:
            # ici fichiers temporaires créés dans dossier local=> stocke dans image du container
            - data_piwigo:/var/www/galleries
            - data_piwigo:/var/www/local
            - data_piwigo:/var/www/plugins
            - data_piwigo:/var/www/themes
            - data_piwigo:/var/www/_data/i
            - data_piwigo:/var/www/upload
            - data_piwigo:/data/var/log
            - data_piwigo:/var/log/apache2
   
        # ports:
        #     - 80:80
    #     req: quand on link dans un container, ça relie dans les deux sens
        links:
            - mysql

    mysql:
        container_name: mysql_piwigo
        image: mysql:8.0.18
        # les utilisateurs sont référencés par rapport au utilisateurs système 
        # => utilisateur peut se connecter s'il utilise le bon mot de passe
        command: ["--default-authentication-plugin=mysql_native_password"]  
        # ports:
        #     - 3306:3306
        volumes:
            - data_mysql:/var/lib/mysql
        environment:
            MYSQL_USER: "${TAG_USER}"
            MYSQL_PASSWORD: "${PASSWORD}"
            MYSQL_DATABASE: "${DATABASE}"
            MYSQL_ROOT_PASSWORD: "true"
    
    ngnix:
        container_name: ngnix_piwigo
        image: nginx:latest
        links:
            - docker-piwigo
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            # ici partage le certificat (mais pour le moment pas généré)
            # ici on fournit des données au container
            #- ./cert:/etc/ngnix/certs
        ports:
            - 80:80
            # pour faire lien https
            # - 443:443
    
# rq: pas de création de réseau car pas nécessaire 
# les containers issus d'un même docker-compose partagent le même réseau par défaut


volumes: 
    data_piwigo:
        driver: local
    data_mysql: 
        driver: local